### ISSUE TITLE
Error creating a sign

### ISSUE THREAD

**Issue by Adriianh** [StylexTV/GSigns#10]
Hello, I have come to report an "error" n.n (I don't know if I can do it here, if not, I'm sorry xD)

I will leave some tests, maybe you will understand better

log: https://pastebin.com/BzG27jBB
Video: https://www.youtube.com/watch?v=dbqsGMRpT7E

**Comment by stylextv** [comment]
Well first of all, when generating a sign based on a file located inside your server, you have to use the "bg-img".
So in your case it would be /gs create {bg-img:map571.png}
You can check out the whole documentation here: https://github.com/StylexTV/GSigns/

But that's not what actually caused the error.
The issue is probably because you run 1.16.1 or 1.16.0
The plugin currently only supports 1.16.2
I will work on that in the future tho

**Comment by stylextv** [comment]
As of the 5.0 update the plugin now supports outdated version like 1.16.1 or 1.16.0 too. Bug fixed. Had to rewrite a lot of the plugins code tho :D But adding newer versions just got a lot easier
