### ISSUE TITLE
Async chunk load blocks current thread in Paper (perhaps Spigot as well)

### ISSUE THREAD

**Issue by CHollasch** [StylexTV/GSigns#14]
https://github.com/StylexTV/GSigns/blob/0438307b6229d08b024859acb78f6a6c888309f1/src/de/stylextv/gs/world/BetterFrame.java#L99

refreshEntityId breaks when the chunk isn't loaded

**Comment by stylextv** [comment]
Hope it's better now.

**Comment by stylextv** [comment]
Oh and I think I have also encountered the effects of this issue, before fixing it, myself.
It was pretty weird. I had one sign whose item frames where inside two chunks and because the 'refreshEntityId' method was executed once a tick on an async thread it completely locked the main thread but for some weird reason the server thread was only locked for those two chunks.
So outside these chunks everything worked: spawning entities, placing blocks, breaking blocks, etc. But inside these two chunks nothing would be registered on the server (Although I could still walk in them).
As an example: I summoned a pig outside and hit it, so it would fly inside the chunks and the moment it crossed the chunk border it would be frozen in place.
I wonder why this strange behaviour occurred.
