### ISSUE TITLE
Signs dissapearing ..again

### ISSUE THREAD

**Issue by ProGitHubUser** [StylexTV/GSigns#16]
No errors, PaperSpigot 1.16.1, latest version of GSigns

Signs vanishing on server restart, and turning into empty item frames

**Comment by stylextv** [comment]
I'm sorry to here that, but since the last free version of GSigns I changed many things within the plugin architecture, so I can't support the free version anymore. I plan to release a paid version, but the Spigot team seems to take a very long time to check a premium resource before releasing it. All I can say now about your problem is that I (and other people) use the latest paper/Spigot versions of version 1.16.3 and there are no problems.
